spring.application.name=miniecom
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=Rohan
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
